name: Android U Action

on:
  push:
    branches: [ "Android-U" ]
  pull_request:
    branches: [ "Android-U" ]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "doc/*"
      - "*.md"
      - ".github/workflows/crowdin.yml"
      - "crowdin.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build App
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: gradle

      - name: Create Sign File
        run: |
          touch signing.properties
          echo storePassword=${{ secrets.KEY_STORE_PASSWORD }} >> signing.properties
          echo keyAlias=${{ secrets.ALIAS }} >> signing.properties
          echo keyPassword='${{ secrets.KEY_STORE_PASSWORD }}' >> signing.properties
          echo storeFile=key.jks >> signing.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks

      - name: Build with Gradle
        if: contains(github.event.head_commit.message, '[skip]') == false
        shell: bash
        run: ./gradlew assembleCanary

      - name: Find APKs
        if: contains(github.event.head_commit.message, '[skip]') == false
        run: |
          echo "APK_FILE_CANARY=$(find app/build/outputs/apk/canary -name '*.apk')" >> $GITHUB_ENV

      - name: Show APKs SHA256
        if: success() && contains(github.event.head_commit.message, '[skip]') == false
        run: |
          echo "### Build Success" >> $GITHUB_STEP_SUMMARY
          echo "|Artifact|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
          canary=($(sha256sum '${{ env.APK_FILE_CANARY }}'))
          echo "|Canary|$canary" >> $GITHUB_STEP_SUMMARY

      - name: Upload Canary APK
        if: contains(github.event.head_commit.message, '[upload]') == true
        uses: actions/upload-artifact@v3
        with:
          name: Cemiuiler Canary
          path: ${{ env.APK_FILE_CANARY }}

      - name: Set up Environment
        shell: bash
        run: |
          export GROUP_ID="${{ secrets.DEBUG_GROUP_ID }}"
          export BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
          export CANARY="${{ env.APK_FILE_CANARY }}"
          export WORKSPACE="${{ github.workspace }}"
          export GIT_CLONE_PATH="$WORKSPACE/git_clone"
          mkdir -p "$GIT_CLONE_PATH"  # Create the git_clone directory
          cd "$GIT_CLONE_PATH"
          git clone ${{ github.event.repository.url }} .

      - name: Generate Git Log
        shell: bash
        run: |
          cd "$GIT_CLONE_PATH"
          git log ${{ github.event.before }}..${{ github.event.after }} --pretty=format:"%h %s" --author="${{ github.event.head_commit.author.name }}" | while read -r line; do
          echo -e '\n' >> "$WORKSPACE/git_log"
          echo -e '*GitHub Action for Main*' >> "$WORKSPACE/git_log"
          commit_id=$(echo "$line" | awk '{print $1}' | sed 's/\(.*\)/[\1]/')
          commit_message=$(echo "$line" | sed 's/\\//g' | awk '{$1=""; print $0}')
          commit_author="by ${{ github.event.head_commit.author.name }}"
          commit_info="${commit_title}\n${commit_message} by *${commit_author}*"
          echo -e "$commit_id $commit_info" >> "$WORKSPACE/git_log"
          done
          ESCAPED="$(cat "$WORKSPACE/git_log" | gawk '{gsub(/[_*[\]()~`>#+=\|{}.!-]/,"\\\\\\\\&")}1' | sed -e 's|"|\\"|g' -e 's|^[0-9a-z]\+|__&__|' | hexdump -v -e '/1 "%02X"' | sed 's/\(..\)/%\1/g')"

      - name: Post to Debug Group
        shell: bash
        run: |
          cd "$WORKSPACE"
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${GROUP_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fcanary%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A\"${ESCAPED}\"%7D%5D" -F canary="@${CANARY}"
